include("test_trainCorrectors_inETM_Couple.jl")
include("test_generateCorrectorOuputs_inETM_Couple.jl")
include("test_generateEnsembleForecasts_Couple.jl")
include("test_trainEnsemble_Couple.jl")
include("test_generateFinalForecast_Couple.jl")